# Generated by Django 3.0.1 on 2020-01-15 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Details',
        ),
    ]
