# Generated by Django 3.0.1 on 2020-01-15 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20200115_2008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Deta',
        ),
    ]
