# Generated by Django 3.0.1 on 2020-01-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20200115_2009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deta',
        ),
    ]
