# Generated by Django 3.0.1 on 2020-01-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_eta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eta',
            old_name='comment',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='eta',
            old_name='date',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='eta',
            old_name='extra',
            new_name='reg',
        ),
        migrations.RemoveField(
            model_name='eta',
            name='extra2',
        ),
        migrations.RemoveField(
            model_name='eta',
            name='month',
        ),
    ]
