# Generated by Django 3.0.1 on 2020-01-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_auto_20200115_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='eta',
            name='im',
            field=models.TextField(default='null'),
        ),
    ]
