# Generated by Django 3.0.1 on 2020-01-17 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_eta_im'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eta',
            name='im',
        ),
        migrations.RemoveField(
            model_name='eta',
            name='image',
        ),
    ]
