# Generated by Django 3.0.1 on 2020-01-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_auto_20200117_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eta',
            name='phone',
            field=models.TextField(),
        ),
    ]
