# Generated by Django 3.0.1 on 2020-01-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('name', models.TextField()),
                ('reg', models.TextField()),
                ('attend', models.IntegerField()),
            ],
        ),
    ]
