# Generated by Django 3.0.1 on 2020-01-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='attend',
            field=models.TextField(),
        ),
    ]
