# Generated by Django 3.0.1 on 2020-01-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200118_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='img',
            field=models.TextField(default='static/current/dist/img/user1-128x128.jpg'),
        ),
    ]
