# Generated by Django 3.0.1 on 2020-01-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_student_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.TextField(),
        ),
    ]
